### ISSUE TITLE
有的查不出来呢?

### ISSUE THREAD

**Issue by whaosoft** [timest/gomanuf#4]
在线的可以查到~~

**Comment by timest** [comment]
不在线的查不到的

**Comment by timest** [comment]
查不到的发一个我看看

**Comment by whaosoft** [comment]
6a:44:fe:bf:55:e4     24:1f:a0:17:6d:9b    48:e2:44:45:0b:04 后俩个在线可以查到  对了 不能提供个QQ或v吗

**Comment by timest** [comment]
近期会更新一下， 我的vx: timest

**Comment by timest** [comment]
> 6a:44:fe:bf:55:e4 24:1f:a0:17:6d:9b 48:e2:44:45:0b:04 后俩个在线可以查到 对了 不能提供个QQ或v吗

已经可以查出来了。  
24:1f:a0:17:6d:9b    Huawei Technologies Co.,Ltd
48:e2:44:45:0b:04  Hon Hai Precision Ind. Co.,Ltd.
